Publish to master
vigojug/vigojug.github.io pull request #10
Opened 2017-03-01 21:31 UTC by antonmry

New version deployed, waiting for the first blog post!

Let me know when is merged to create the first event in the meetup :tada:

2017-03-01 21:35 UTC, tomasalmeida commented on output/blog/2013/first-post.html
> +ligula. Vestibulum tristique odio ut risus ultricies a hendrerit quam iaculis. Duis tempor elit sit amet
este se coló no?

2017-03-01 21:36 UTC, tomasalmeida commented on output/blog/2013/fourth-post.html
> +ligula. Vestibulum tristique odio ut risus ultricies a hendrerit quam iaculis. Duis tempor elit sit amet
y este tb

2017-03-01 21:38 UTC, tomasalmeida requested changes
Creo que se te colaron algunos ficheros fuente.

2017-03-01 21:38 UTC, tomasalmeida commented on output/blog/2013/second-post.html
> +    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
otro :-)

2017-03-01 21:39 UTC, tomasalmeida commented
Creo que tenías unos ficheros de prueba y se te acabaron colando en la versión final.

2017-03-02 07:07 UTC, antonmry commented
You are totally wrong. I'm used to the gradle plugin which I launch with `clean`... I updated also the README.

2017-03-02 07:18 UTC, tomasalmeida approved these changes

2017-03-02 07:19 UTC, merged